-- AssetIds.lua  (auto-generated by bulk_upload_assets.py)
-- All IDs uploaded via Roblox Open Cloud

local AssetIds = {}

-- ===== HUD ICONS =====
AssetIds.coin                     = "rbxassetid://105815187147426"
AssetIds.gem                      = "rbxassetid://109043593895795"
AssetIds.robux                    = "rbxassetid://122844087936130"
AssetIds.paw                      = "rbxassetid://86184733003162"
AssetIds.scratch                  = "rbxassetid://82971140213252"
AssetIds.pie                      = "rbxassetid://113931316817845"
AssetIds.fish                     = "rbxassetid://82417050202857"
AssetIds.slushie                  = "rbxassetid://99243112278541"
AssetIds.tp                       = "rbxassetid://125472864196470"
AssetIds.anvil                    = "rbxassetid://108161487320119"
AssetIds.skull                    = "rbxassetid://130389117491928"
AssetIds.wings                    = "rbxassetid://95189137248435"
AssetIds.shop                     = "rbxassetid://99634099519879"
AssetIds.bag                      = "rbxassetid://129592456732256"
AssetIds.bars                     = "rbxassetid://81142329231817"
AssetIds.gift                     = "rbxassetid://89951750603046"
AssetIds.slot                     = "rbxassetid://72948932908042"
AssetIds.star                     = "rbxassetid://136693073118900"
AssetIds.trophy                   = "rbxassetid://112096827446057"

-- ===== TEXTURES =====
AssetIds.asphalt                  = "rbxassetid://87906279864313"
AssetIds.brick                    = "rbxassetid://116534164857454"
AssetIds.concrete                 = "rbxassetid://80198486264577"
AssetIds.fur_orange               = "rbxassetid://96281501423477"
AssetIds.grass                    = "rbxassetid://73817717455234"
AssetIds.neon_sign                = "rbxassetid://122168511391603"
AssetIds.skyscraper_windows       = "rbxassetid://105109450915340"

-- ===== SOUNDS (already uploaded) =====
AssetIds.anvil_clang              = "rbxassetid://128055965356130"
AssetIds.cat_scratch              = "rbxassetid://80128569475740"
AssetIds.coin_pickup              = "rbxassetid://120402840139184"
AssetIds.fish_slap                = "rbxassetid://96456436763335"
AssetIds.flight_whoosh            = "rbxassetid://119520323684729"
AssetIds.ko_sound                 = "rbxassetid://121032018696220"
AssetIds.level_up                 = "rbxassetid://127196866088823"
AssetIds.meow_1                   = "rbxassetid://97790714003696"
AssetIds.meow_2                   = "rbxassetid://130271609785911"
AssetIds.meow_3                   = "rbxassetid://82168671886561"
AssetIds.pie_splat                = "rbxassetid://74973417399679"
AssetIds.purrgatory               = "rbxassetid://124790773952159"
AssetIds.slushie_freeze           = "rbxassetid://127263280391632"
AssetIds.spawn_chime              = "rbxassetid://88974946443069"
AssetIds.tp_unroll                = "rbxassetid://106817307887848"

-- ===== SOUNDS — TODO upload, then paste id here. AssetIds.has() returns
-- false for "rbxassetid://0", so all consuming code falls back gracefully. =====
AssetIds.cop_siren                = "rbxassetid://86988635646392"  -- looping siren, attached to cop head, SFX channel
AssetIds.boss_warning             = "rbxassetid://125994595152418"  -- one-shot stinger when boss spawns, SFX channel
AssetIds.quest_complete           = "rbxassetid://78247148900142"  -- one-shot chime when quest finishes, UI channel
AssetIds.city_ambient             = "rbxassetid://104379163206023"  -- looping background music, Music channel
AssetIds.cat_purr_loop            = "rbxassetid://85676718403186"  -- looping purr for emote, SFX channel
AssetIds.cat_hiss                 = "rbxassetid://96907205236145"  -- short hiss for emote, SFX channel
AssetIds.ticket_buzz              = "rbxassetid://123900645230046"  -- short angry buzz when cop tickets you

-- ===== MESHES (already uploaded) =====
AssetIds.mesh_anvil               = "rbxassetid://112707712825379"
AssetIds.mesh_brownstone          = "rbxassetid://121998943640862"
AssetIds.mesh_cat_body            = "rbxassetid://123706210309343"
AssetIds.mesh_cat_ear             = "rbxassetid://76952531040076"
AssetIds.mesh_cat_head            = "rbxassetid://77371552407335"
AssetIds.mesh_cat_leg             = "rbxassetid://76441569259757"
AssetIds.mesh_cat_tail            = "rbxassetid://133915962991980"
AssetIds.mesh_hydrant             = "rbxassetid://127792061456861"
AssetIds.mesh_mailbox             = "rbxassetid://108850793265324"
AssetIds.mesh_pie                 = "rbxassetid://140111034397281"
AssetIds.mesh_skyscraper          = "rbxassetid://82803902927729"
AssetIds.mesh_taxi                = "rbxassetid://107507236907511"
AssetIds.mesh_trashcan            = "rbxassetid://83811237643216"

-- ===== MESHES — TODO build via blender_kittyraiser_extras.py, upload, paste
-- id here. CityRebuild + CopSystem already check AssetIds.has() and fall
-- back to primitive shapes if not yet uploaded. =====
AssetIds.mesh_cop_car             = "rbxassetid://98613909152204"  -- black/white squad car, used by CopSystem
AssetIds.mesh_streetlamp          = "rbxassetid://108783803216240"  -- decorative lamp post, downtown zone
AssetIds.mesh_park_bench          = "rbxassetid://92447349930392"  -- plaza seating
AssetIds.mesh_oak_tree            = "rbxassetid://132486586497203"  -- replaces procedural tree in suburbs
AssetIds.mesh_palm_tree           = "rbxassetid://77941301827213"  -- replaces procedural tree in harbor
AssetIds.mesh_donut               = "rbxassetid://129581868885842"  -- food prop for survival eating
AssetIds.mesh_coffee              = "rbxassetid://73626441372959"  -- drink prop for thirst
AssetIds.mesh_manhole             = "rbxassetid://134150158459009"  -- flush ground decoration, downtown
AssetIds.mesh_fire_truck          = "rbxassetid://98411832064235"  -- ambient prop in suburbs


-- ===== V2 CITY MESHES (Phase 10 - cartoon city + street furniture) =====
AssetIds.mesh_taxi_yellow           = "rbxassetid://138033436650428"
AssetIds.mesh_delivery_van          = "rbxassetid://133553244193800"
AssetIds.mesh_food_truck            = "rbxassetid://99741262168886"
AssetIds.mesh_fire_hydrant          = "rbxassetid://107488733988709"
AssetIds.mesh_trash_can             = "rbxassetid://103504006010745"
AssetIds.mesh_mailbox_blue          = "rbxassetid://71802550356350"
AssetIds.mesh_bus_stop_shelter      = "rbxassetid://103935174726610"
AssetIds.mesh_traffic_light         = "rbxassetid://116494841104667"
AssetIds.mesh_hot_dog_cart          = "rbxassetid://90205212501591"
AssetIds.mesh_skyscraper_chunk      = "rbxassetid://102528222902039"

-- ===== CAT ANIMATIONS — TODO upload via Roblox Studio Animation Editor
-- and paste IDs here. CatAnimations.server.lua reads these and patches the
-- default Animate script's StringValue children. Falls back to default Roblox
-- humanoid anims if any are still 0. =====
AssetIds.anim_cat_idle            = "rbxassetid://0"
AssetIds.anim_cat_walk            = "rbxassetid://0"
AssetIds.anim_cat_run             = "rbxassetid://0"
AssetIds.anim_cat_jump            = "rbxassetid://0"
AssetIds.anim_cat_fall            = "rbxassetid://0"

-- ===== BADGES — TODO create in Creator Hub > Badges, paste IDs here.
-- AchievementSystem.server only awards if AssetIds.has() returns true. =====
AssetIds.badge_first_prank        = "rbxassetid://1429423254055989"
AssetIds.badge_level_10           = "rbxassetid://2479335747751103"
AssetIds.badge_level_25           = "rbxassetid://2206460901927124"
AssetIds.badge_level_50           = "rbxassetid://0"
AssetIds.badge_level_100          = "rbxassetid://0"
AssetIds.badge_first_rebirth      = "rbxassetid://0"
AssetIds.badge_boss_defeat        = "rbxassetid://0"
AssetIds.badge_ticketed           = "rbxassetid://0"

-- ===== MARKETING =====
AssetIds.game_icon                = "rbxassetid://92376623612256"
AssetIds.game_icon_small          = "rbxassetid://92376623612256"
AssetIds.thumb_anvil_drop         = "rbxassetid://101925244771007"
AssetIds.thumb_city_night         = "rbxassetid://78180746183552"
AssetIds.thumb_lobby              = "rbxassetid://102793817013440"
AssetIds.thumb_pie_throw          = "rbxassetid://98108593160983"

function AssetIds.has(name)
    local v = AssetIds[name]
    return type(v) == "string" and v ~= "rbxassetid://0" and v ~= ""
end
function AssetIds.get(name)
    if AssetIds.has(name) then return AssetIds[name] end
    return nil
end

return AssetIds