-- AssetIds.lua  (auto-generated by bulk_upload_assets.py)
-- All IDs uploaded via Roblox Open Cloud

local AssetIds = {}

-- ===== HUD ICONS =====
AssetIds.coin                     = "rbxassetid://105815187147426"
AssetIds.gem                      = "rbxassetid://109043593895795"
AssetIds.robux                    = "rbxassetid://122844087936130"
AssetIds.paw                      = "rbxassetid://86184733003162"
AssetIds.scratch                  = "rbxassetid://82971140213252"
AssetIds.pie                      = "rbxassetid://113931316817845"
AssetIds.fish                     = "rbxassetid://82417050202857"
AssetIds.slushie                  = "rbxassetid://99243112278541"
AssetIds.tp                       = "rbxassetid://125472864196470"
AssetIds.anvil                    = "rbxassetid://108161487320119"
AssetIds.skull                    = "rbxassetid://130389117491928"
AssetIds.wings                    = "rbxassetid://95189137248435"
AssetIds.shop                     = "rbxassetid://99634099519879"
AssetIds.bag                      = "rbxassetid://129592456732256"
AssetIds.bars                     = "rbxassetid://81142329231817"
AssetIds.gift                     = "rbxassetid://89951750603046"
AssetIds.slot                     = "rbxassetid://72948932908042"
AssetIds.star                     = "rbxassetid://136693073118900"
AssetIds.trophy                   = "rbxassetid://112096827446057"

-- ===== TEXTURES =====
AssetIds.asphalt                  = "rbxassetid://87906279864313"
AssetIds.brick                    = "rbxassetid://116534164857454"
AssetIds.concrete                 = "rbxassetid://80198486264577"
AssetIds.fur_orange               = "rbxassetid://96281501423477"
AssetIds.grass                    = "rbxassetid://73817717455234"
AssetIds.neon_sign                = "rbxassetid://122168511391603"
AssetIds.skyscraper_windows       = "rbxassetid://105109450915340"

-- ===== SOUNDS =====
AssetIds.anvil_clang              = "rbxassetid://128055965356130"
AssetIds.cat_scratch              = "rbxassetid://80128569475740"
AssetIds.coin_pickup              = "rbxassetid://120402840139184"
AssetIds.fish_slap                = "rbxassetid://96456436763335"
AssetIds.flight_whoosh            = "rbxassetid://119520323684729"
AssetIds.ko_sound                 = "rbxassetid://121032018696220"
AssetIds.level_up                 = "rbxassetid://127196866088823"
AssetIds.meow_1                   = "rbxassetid://97790714003696"
AssetIds.meow_2                   = "rbxassetid://130271609785911"
AssetIds.meow_3                   = "rbxassetid://82168671886561"
AssetIds.pie_splat                = "rbxassetid://74973417399679"
AssetIds.purrgatory               = "rbxassetid://124790773952159"
AssetIds.slushie_freeze           = "rbxassetid://127263280391632"
AssetIds.spawn_chime              = "rbxassetid://88974946443069"
AssetIds.tp_unroll                = "rbxassetid://106817307887848"

-- ===== MESHES =====
AssetIds.mesh_anvil               = "rbxassetid://112707712825379"
AssetIds.mesh_brownstone          = "rbxassetid://121998943640862"
AssetIds.mesh_cat_body            = "rbxassetid://123706210309343"
AssetIds.mesh_cat_ear             = "rbxassetid://76952531040076"
AssetIds.mesh_cat_head            = "rbxassetid://77371552407335"
AssetIds.mesh_cat_leg             = "rbxassetid://76441569259757"
AssetIds.mesh_cat_tail            = "rbxassetid://133915962991980"
AssetIds.mesh_hydrant             = "rbxassetid://127792061456861"
AssetIds.mesh_mailbox             = "rbxassetid://108850793265324"
AssetIds.mesh_pie                 = "rbxassetid://140111034397281"
AssetIds.mesh_skyscraper          = "rbxassetid://82803902927729"
AssetIds.mesh_taxi                = "rbxassetid://107507236907511"
AssetIds.mesh_trashcan            = "rbxassetid://83811237643216"

-- ===== MARKETING =====
AssetIds.game_icon                = "rbxassetid://112119672948925"
AssetIds.game_icon_small          = "rbxassetid://127301758963300"
AssetIds.thumb_anvil_drop         = "rbxassetid://122430493238064"
AssetIds.thumb_city_night         = "rbxassetid://93412783927707"
AssetIds.thumb_lobby              = "rbxassetid://138479515559252"
AssetIds.thumb_pie_throw          = "rbxassetid://77814614183684"

function AssetIds.has(name)
    local v = AssetIds[name]
    return type(v) == "string" and v ~= "rbxassetid://0" and v ~= ""
end
function AssetIds.get(name)
    if AssetIds.has(name) then return AssetIds[name] end
    return nil
end

return AssetIds