#!/usr/bin/env python3
"""
build_loader.py — emit a Studio-pasteable Lua installer from src/.

Walks the src/ tree, classifies each .lua file (Script / LocalScript /
ModuleScript) by suffix and parent folder, and emits a single Lua file
that can be pasted into the Studio command bar to materialize the entire
codebase as Studio Instances.

If the resulting file exceeds CHUNK_LIMIT bytes, splits it into
build/install_part_1.lua, build/install_part_2.lua, ... so each piece
fits within the command-bar paste budget.

Usage:
    python3 build_loader.py
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
OUT_DIR = ROOT / "build"
CHUNK_LIMIT = 180_000  # bytes per generated file; under Studio command bar's paste budget


def classify(rel_path: Path) -> tuple[str, list[str]]:
    """Return (className, breadcrumbs) for a source file under src/.

    breadcrumbs is the Instance hierarchy under DataModel, e.g.
    ['ReplicatedStorage', 'Modules', 'GameConfig'] for a module named
    GameConfig.lua.
    """
    parts = list(rel_path.parts)
    # parts[0] = top-level service name (ReplicatedStorage, ServerScriptService, ...)
    # parts[-1] = file name with extension(s)
    file_name = parts[-1]
    parent_chain = parts[:-1]

    # Strip suffix to get the Studio Instance Name.
    if file_name.endswith(".server.lua"):
        kind = "Script"
        name = file_name[: -len(".server.lua")]
    elif file_name.endswith(".client.lua"):
        kind = "LocalScript"
        name = file_name[: -len(".client.lua")]
    elif file_name.endswith(".lua"):
        kind = "ModuleScript"
        name = file_name[: -len(".lua")]
    else:
        raise ValueError(f"unknown file type: {rel_path}")

    return kind, [*parent_chain, name]


def lua_long_string(source: str) -> str:
    """Wrap source in a Lua long-bracket string with a unique level so embedded
    ]] (or ]=]) sequences don't break out.
    """
    level = 0
    while ("]" + ("=" * level) + "]") in source:
        level += 1
    eq = "=" * level
    return f"[{eq}[\n{source}\n]{eq}]"


def emit_header(handle, version: str) -> None:
    handle.write(
        "-- KittyRaiser one-paste installer\n"
        "-- Generated by build_loader.py from src/.\n"
        "-- Paste into the Studio command bar (View > Command Bar) and press Enter.\n"
        f"-- Build version: {version}\n"
        "\n"
        "local function ensure(parent, className, name)\n"
        "    local existing = parent:FindFirstChild(name)\n"
        "    if existing and existing.ClassName == className then return existing end\n"
        "    if existing then existing:Destroy() end\n"
        "    local inst = Instance.new(className)\n"
        "    inst.Name = name\n"
        "    inst.Parent = parent\n"
        "    return inst\n"
        "end\n"
        "\n"
        "local function ensureFolder(parent, name)\n"
        "    return ensure(parent, 'Folder', name)\n"
        "end\n"
        "\n"
        "local function writeScript(parentPath, className, source)\n"
        "    -- parentPath is a list like {'ReplicatedStorage','Modules','GameConfig'}\n"
        "    local node = game\n"
        "    for i = 1, #parentPath - 1 do\n"
        "        local segment = parentPath[i]\n"
        "        local nxt = node:FindFirstChild(segment)\n"
        "        if not nxt then\n"
        "            -- Top-level services already exist; create only Folder children.\n"
        "            nxt = ensureFolder(node, segment)\n"
        "        end\n"
        "        node = nxt\n"
        "    end\n"
        "    local leafName = parentPath[#parentPath]\n"
        "    local s = ensure(node, className, leafName)\n"
        "    s.Source = source\n"
        "    return s\n"
        "end\n"
        "\n"
        "local INSTALLED = 0\n"
        "local function W(parentPath, className, source)\n"
        "    writeScript(parentPath, className, source)\n"
        "    INSTALLED = INSTALLED + 1\n"
        "end\n"
        "\n"
    )


def emit_footer(handle) -> None:
    handle.write(
        "\nprint(('[KittyRaiser installer] %d scripts written'):format(INSTALLED))\n"
    )


def collect_sources() -> list[tuple[Path, str, list[str], str]]:
    files: list[tuple[Path, str, list[str], str]] = []
    for path in sorted(SRC.rglob("*.lua")):
        rel = path.relative_to(SRC)
        kind, breadcrumbs = classify(rel)
        source = path.read_text(encoding="utf-8")
        files.append((rel, kind, breadcrumbs, source))
    return files


def write_combined(files, version):
    OUT_DIR.mkdir(exist_ok=True)
    body_chunks: list[str] = []
    for rel, kind, breadcrumbs, source in files:
        path_lua = "{" + ",".join(f"'{seg}'" for seg in breadcrumbs) + "}"
        body_chunks.append(
            f"-- {rel}\n"
            f"W({path_lua}, '{kind}', {lua_long_string(source)})\n\n"
        )
    body = "".join(body_chunks)

    # Try a single combined file first.
    combined_path = OUT_DIR / "install.lua"
    with combined_path.open("w", encoding="utf-8") as fh:
        emit_header(fh, version)
        fh.write(body)
        emit_footer(fh)

    if combined_path.stat().st_size <= CHUNK_LIMIT:
        return [combined_path]

    # Split into chunks. Each chunk gets its own header (idempotent) so users
    # can paste them in order without state crossing files.
    combined_path.unlink()
    chunks: list[Path] = []
    current_size = 0
    current_buf: list[str] = []
    chunk_idx = 1

    def flush():
        nonlocal current_buf, current_size, chunk_idx
        if not current_buf:
            return
        path = OUT_DIR / f"install_part_{chunk_idx}.lua"
        with path.open("w", encoding="utf-8") as fh:
            emit_header(fh, f"{version} (part {chunk_idx})")
            fh.write("".join(current_buf))
            emit_footer(fh)
        chunks.append(path)
        current_buf = []
        current_size = 0
        chunk_idx += 1

    for rel, kind, breadcrumbs, source in files:
        path_lua = "{" + ",".join(f"'{seg}'" for seg in breadcrumbs) + "}"
        entry = (
            f"-- {rel}\n"
            f"W({path_lua}, '{kind}', {lua_long_string(source)})\n\n"
        )
        if current_size + len(entry) > CHUNK_LIMIT and current_buf:
            flush()
        current_buf.append(entry)
        current_size += len(entry)
    flush()
    return chunks


def main() -> int:
    if not SRC.is_dir():
        print(f"src/ not found at {SRC}", file=sys.stderr)
        return 1
    version = os.environ.get("KITTYRAISER_VERSION", "dev")
    files = collect_sources()
    paths = write_combined(files, version)
    total_bytes = sum(p.stat().st_size for p in paths)
    if len(paths) == 1:
        print(f"Wrote {paths[0].relative_to(ROOT)} ({total_bytes:,} bytes, {len(files)} scripts)")
    else:
        print(f"Wrote {len(paths)} chunks under build/ ({total_bytes:,} bytes total, {len(files)} scripts):")
        for p in paths:
            print(f"  {p.relative_to(ROOT)}  ({p.stat().st_size:,} bytes)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
