#!/usr/bin/env python3
"""
parse_asset_dump.py
Reads asset-ID dump output (paste from Studio Output panel), generates AssetIds.lua.

Usage:
  pbpaste | python3 parse_asset_dump.py > AssetIds.lua

Or:
  python3 parse_asset_dump.py < dumped_output.txt > AssetIds.lua

Looks for lines like:
  ICON: coin = rbxassetid://1234567890
  TEXTURE: brick = rbxassetid://...
  SOUND: meow_1 = rbxassetid://...
  MESH: cat_body = rbxassetid://...
"""

import sys
import re

ICON_KEYS = ["coin","gem","robux","paw","scratch","pie","fish","slushie","tp",
             "anvil","skull","wings","shop","bag","bars","gift","slot","star","trophy"]
TEX_KEYS = ["asphalt","brick","concrete","fur_orange","grass","neon_sign","skyscraper_windows"]
SOUND_KEYS = ["anvil_clang","cat_scratch","coin_pickup","fish_slap","flight_whoosh",
              "ko_sound","level_up","meow_1","meow_2","meow_3","pie_splat",
              "purrgatory","slushie_freeze","spawn_chime","tp_unroll"]
MESH_KEYS = ["anvil","brownstone","cat_body","cat_ear","cat_head","cat_leg",
             "cat_tail_segment","hydrant","mailbox","pie","skyscraper","taxi","trashcan"]

# Mesh aliases: AssetIds.lua uses mesh_xxx prefix
MESH_ALIAS = {
    "anvil": "mesh_anvil",
    "brownstone": "mesh_brownstone",
    "cat_body": "mesh_cat_body",
    "cat_ear": "mesh_cat_ear",
    "cat_head": "mesh_cat_head",
    "cat_leg": "mesh_cat_leg",
    "cat_tail_segment": "mesh_cat_tail",
    "hydrant": "mesh_hydrant",
    "mailbox": "mesh_mailbox",
    "pie": "mesh_pie",
    "skyscraper": "mesh_skyscraper",
    "taxi": "mesh_taxi",
    "trashcan": "mesh_trashcan",
}
TEX_ALIAS = {
    "neon_sign": "neon_sign",          # consistent
    "skyscraper_windows": "skyscraper_windows",
}

LINE_RE = re.compile(r"^\s*(ICON|TEXTURE|SOUND|MESH):\s*(\S+)\s*=\s*(rbxassetid://\d+)\s*$", re.IGNORECASE)

def main():
    raw = sys.stdin.read()
    found = {"ICON": {}, "TEXTURE": {}, "SOUND": {}, "MESH": {}}
    for line in raw.splitlines():
        m = LINE_RE.match(line)
        if not m: continue
        kind = m.group(1).upper()
        name = m.group(2).strip()
        rid = m.group(3).strip()
        found[kind][name] = rid

    def fmt(name, key_list, alias_map=None):
        out = []
        for k in key_list:
            target = (alias_map.get(k, k) if alias_map else k)
            v = found.get(name, {}).get(k, "rbxassetid://0")
            out.append(f'AssetIds.{target:<24} = "{v}"')
        return "\n".join(out)

    lines = []
    lines.append('-- AssetIds.lua  (auto-generated by parse_asset_dump.py)')
    lines.append('-- Place in: ReplicatedStorage > Modules > AssetIds (ModuleScript)')
    lines.append('')
    lines.append('local AssetIds = {}')
    lines.append('')
    lines.append('-- ===== HUD ICONS =====')
    lines.append(fmt("ICON", ICON_KEYS))
    lines.append('')
    lines.append('-- ===== TEXTURES =====')
    lines.append(fmt("TEXTURE", TEX_KEYS, TEX_ALIAS))
    lines.append('')
    lines.append('-- ===== SOUNDS =====')
    lines.append(fmt("SOUND", SOUND_KEYS))
    lines.append('')
    lines.append('-- ===== MESHES =====')
    lines.append(fmt("MESH", MESH_KEYS, MESH_ALIAS))
    lines.append('')
    lines.append('function AssetIds.has(name)')
    lines.append('    local v = AssetIds[name]')
    lines.append('    return type(v) == "string" and v ~= "rbxassetid://0" and v ~= ""')
    lines.append('end')
    lines.append('function AssetIds.get(name)')
    lines.append('    if AssetIds.has(name) then return AssetIds[name] end')
    lines.append('    return nil')
    lines.append('end')
    lines.append('')
    lines.append('return AssetIds')

    print("\n".join(lines))

    # Also print a summary to stderr so user can see hit rate
    found_count = sum(len(v) for v in found.values())
    expected = len(ICON_KEYS) + len(TEX_KEYS) + len(SOUND_KEYS) + len(MESH_KEYS)
    sys.stderr.write(f"\n[parse_asset_dump] resolved {found_count}/{expected} asset IDs\n")
    for kind, items in found.items():
        if items:
            sys.stderr.write(f"  {kind}: {len(items)} found ({', '.join(sorted(items.keys()))})\n")
        else:
            sys.stderr.write(f"  {kind}: 0 found (none in input)\n")

if __name__ == "__main__":
    main()
